//$tab Main------------------------------------------------------------------------------------------------------------

SET ThousandSep=' ';
SET DecimalSep=',';
SET MoneyThousandSep=' ';
SET MoneyDecimalSep=',';
SET MoneyFormat='# ##0,00 ₽;-# ##0,00 ₽';
SET TimeFormat='h:mm:ss';
SET DateFormat='DD.MM.YYYY';
SET TimestampFormat='DD.MM.YYYY hh:mm:ss[.fff]';
SET FirstWeekDay=0;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='ru-RU';
SET CreateSearchIndexOnReload=0;
SET MonthNames='янв.;февр.;мар.;апр.;мая;июн.;июл.;авг.;сент.;окт.;нояб.;дек.';
SET LongMonthNames='январь;февраль;март;апрель;май;июнь;июль;август;сентябрь;октябрь;ноябрь;декабрь';
SET DayNames='пн;вт;ср;чт;пт;сб;вс';
SET LongDayNames='понедельник;вторник;среда;четверг;пятница;суббота;воскресенье';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

//===================================================================
set vDBQvdPath=[lib://OLAP (fixmt_stefanovich)/];
set vQVDPath=[lib://ETL (fixmt_stefanovich)/];
set vExcelPath=[lib://Excel (fixmt_stefanovich)/];
//===================================================================
let FullReload=0;
//===================================================================
let DateStart = date(MakeDate(2023,1,1));
let DateFinish = date(today(1));
let RollBackMonthCount = IF(FullReload=1,25,2);
//let RollBackMonthCount = IF(FullReload=1,35,IF(match(num(WeekDay(today(2))),5,6),35,3)); 
 
//===================================================================
LIB CONNECT TO 'UT-PLAYH (fixmt_stefanovich)'; //Продуктив
//LIB CONNECT TO 'UT-PLAYH (fixmt_esipovich)';
//===================================================================



//$tab РеализацияТоваровУслуг_1С------------------------------------------------------------------------------------

//Документ.РеализацияТоваровУслуг 
РеализацияТоваровУслуг:
LOAD *;	
SQL SELECT 
	_IDRRef as Ссылка,
    _NumberPrefix as Дата,
    _Fld5057RRef as КодСклад,
    _Fld5047RRef as ТипПродажи,
    _Fld5065 as Сумма_бн,
	_Fld5112 as НДС_бн,
	_Fld20196 as СебесбНДС_бн 
FROM "UT-PLAYH".dbo."_Document299"
WHERE _Posted=1 and _Marked=0;

left join 
load *;
SQL SELECT
    (_Document299_IDRRef) as Ссылка,
    Sum(_Fld5119) as Количество_бн,
	Sum(_Fld5127) as Сумма1,
	Sum(_Fld5128) as СуммаНДС1,
	Sum(_Fld5138)as Себес1
FROM "UT-PLAYH".dbo."_Document299_VT5114"
	Group by _Document299_IDRRef;

Left Join
load *;
SQL SELECT
	(_IDRRef) as КодСклад,
	_Fld12835 as shopindex
FROM "UT-PLAYH".dbo."_Reference132";
// LOAD
// 	Text(_IDRRef) as КодСклад,
//     //_Description as  Склад,
//     //_Fld12772 as Город,
//     _Fld12835 as shopindex
// FROM [$(vDBQvdPath)/_Reference/_Reference132.qvd](qvd);
store РеализацияТоваровУслуг into  [$(vQVDPath)/SET/РеализацияТоваровУслуг_1С.qvd](qvd);
drop table РеализацияТоваровУслуг;
//exit script;


//$tab SET Таблицы--------------------------------------------------------------------------

/*
Чеки - od_purchase - кол-во и сумма чеков

*/

LIB CONNECT TO 'set_operday (fixmt_esipovich)';

let DateInc = DateStart;
let DateLoadTo = DateFinish; 

do
	let DateFrom = DateInc; 
	let DateTo = MonthEnd(DateInc);
	let DateToSQL = date(MonthEnd(DateInc)+1);
	let FileSuffix = Text(date(AddYears(DateInc,-0),'YYYY_MM'));
	let InRollBack  = (DateInc>=AddMonths(DateLoadTo, -RollBackMonthCount));	

if InRollBack or isnull(FileSize('$(QVDPath)/SET/od_purchase/od_purchase_$(FileSuffix).qvd')) then

TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

LOAD *;
[od_purchase]:
SQL SELECT
	id,
    id_shift,
	datecommit as Дата,
    operationtype,
    checksumend
FROM public.od_purchase
where datecommit>= '$(DateFrom)' and datecommit< '$(DateToSQL)' and checkstatus=0 ;

left join (od_purchase)
LOAD *;
//[od_position]:
SQL SELECT
	id_purchase as id,
    Count(id) as strok,
	SUM(ndssum) as NDS,
    SUM(qnty)/1000 as qty_item
FROM public.od_position
where datecommit>= '$(DateFrom)' and datecommit< '$(DateToSQL)' 
group by id_purchase;

left join (od_purchase)
LOAD *;
//[od_shift]:
SQL SELECT
	id as id_shift,
    shopindex
	FROM public.od_shift
	where operday>= '$(DateFrom)' and operday< '$(DateToSQL)'// and shopindex<>350
    group by id;
    
left join (od_purchase)
LOAD *;
//[od_payment]:
SQL SELECT
	id_purchase as id,
    paymentclass
	FROM public.od_payment
    where datecommit>= '$(DateFrom)' and datecommit< '$(DateToSQL)' and paymentclass=0;
	
store od_purchase into [$(QVDPath)/SET/od_purchase/od_purchase_$(FileSuffix).qvd](qvd);
drop table od_purchase;
ENDIF


// if InRollBack or isnull(FileSize('$(QVDPath)/SET/1c_data/1c_data_$(FileSuffix).qvd')) then
	
// LOAD *;
// [od_shift]:
// SQL SELECT
// 	operday as Дата,
//     Count(Distinct shopindex) as qtyto //к-во работающих ТО в день 
// FROM public.od_shift
// where operday>= '$(DateFrom)' and operday< '$(DateToSQL)'
// group by operday; 
// join (od_shift)

// [1c_data]:
// Load
// 	Дата,
//     Sum(if ("ТипДокумент"='000000C5' OR "ТипДокумент"='0000010E',"Себестоимость",0)) as себес_н
// //     Sum(if ("ТипДокумент"='0000012B', "#Сумма реализации с НДС", 0)) as бнндс,
// //     Sum(if ("ТипДокумент"='0000012B', "#Сумма реализации без НДС", 0)) as бнбндс
//     FROM [$(vQVDPath)\РегистрыНакоплений\ПартииТоваровНаСкладах\ПартииТоваровНаСкладах_$(FileSuffix).qvd](qvd)
//     Group by Дата;

// store [1c_data] into [$(QVDPath)/SET/1c_data/1c_data_$(FileSuffix).qvd](qvd);
// drop table [1c_data];

// ENDIF
let DateInc = timestamp(AddMonths(DateInc, 1));
LOOP while not InMonth(DateInc, DateLoadTo, 1);

План:
LOAD 
    Date(Дата) as Дата,
    план_выручка,
    план_трафик,
    план_срчек,
    план_то,
    план_вп,
    'Ambition plan' as [Тип плана]
FROM [$(vExcelPath)/oper_plan.xlsx] (ooxml, embedded labels);

join(План)
LOAD 
    Date(Дата) as Дата,
    план_выручка,
    план_трафик,
    план_срчек,
    план_то,
    план_вп,
    'Base plan' as [Тип плана]
FROM [$(vExcelPath)/oper_plan_base.xlsx] (ooxml, embedded labels);

store План into [$(vQVDPath)/SET/oper_plan.qvd](qvd);
drop table План;
//exit script;


//$tab Счетчики посетителей-------------------------------------------------------

LIB CONNECT TO 'Countmax (fixmt_esipovich)';

let DateInc = DateStart;
let DateLoadTo = DateFinish; 

do
	let DateFrom = DateInc; 
	let DateTo = MonthEnd(DateInc);
	let DateToSQL = date(MonthEnd(DateInc)+1);
	let FileSuffix = Text(date(AddYears(DateInc,-0),'YYYY_MM'));
	let InRollBack  = (DateInc>=AddMonths(DateLoadTo, -RollBackMonthCount));	

if InRollBack or isnull(FileSize('$(QVDPath)/SET/od_purchase/od_purchase_$(FileSuffix).qvd')) then

	
TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

LOAD *;
[visitors]:
SELECT 	cmse.ID_Enter, 
		cme.NameEnter, 
        cast(RIGHT(cme.NameEnter, (len(cme.NameEnter)-PATINDEX('%[1-9]%',cme.NameEnter)+1)) as int) as shopindex, 
		//cmse.TimeRecord as Дата,
      	convert(date,cmse.TimeRecord,104) as Дата,
		DATEPART(hour, cmse.TimeRecord) as час,
		Sum(cmse.SumIn+cmse.SumOut)/2 as чел
        //cmse.SumIn as visitors_in,
		//cmse.SumOut as visitors_out
FROM Countmax.dbo.CM_StorageEnter as cmse
join Countmax.dbo.Cm_Enter as cme on cmse.ID_Enter = cme.ID_Enter
where Convert(date,cmse.TimeRecord,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,cmse.TimeRecord,104)< Convert(date,'$(DateToSQL)',104)
and cmse.SumIn<>0 and cmse.SumOut<>0 and cme.ID_Project = '115449266'
group by cmse.ID_Enter, cme.NameEnter, convert(date,cmse.TimeRecord,104), DATEPART(hour, cmse.TimeRecord); 

store visitors into [$(QVDPath)/Countmax/visitors/visitors_$(FileSuffix).qvd](qvd);
drop table visitors;
ENDIF

let DateInc = timestamp(AddMonths(DateInc, 1));
LOOP while not InMonth(DateInc, DateLoadTo, 1);