//$tab Main

SET ThousandSep=' ';
SET DecimalSep=',';
SET MoneyThousandSep=' ';
SET MoneyDecimalSep=',';
SET MoneyFormat='# ##0,00 ₽;-# ##0,00 ₽';
SET TimeFormat='h:mm:ss';
SET DateFormat='DD.MM.YYYY';
SET TimestampFormat='DD.MM.YYYY h:mm:ss[.fff]';
SET FirstWeekDay=0;
SET BrokenWeeks=1;
SET ReferenceDay=0;
SET FirstMonthOfYear=1;
SET CollationLocale='ru-RU';
SET CreateSearchIndexOnReload=0;
SET MonthNames='янв.;февр.;мар.;апр.;мая;июн.;июл.;авг.;сент.;окт.;нояб.;дек.';
SET LongMonthNames='январь;февраль;март;апрель;май;июнь;июль;август;сентябрь;октябрь;ноябрь;декабрь';
SET DayNames='пн;вт;ср;чт;пт;сб;вс';
SET LongDayNames='понедельник;вторник;среда;четверг;пятница;суббота;воскресенье';
SET NumericalAbbreviation='3:k;6:M;9:G;12:T;15:P;18:E;21:Z;24:Y;-3:m;-6:μ;-9:n;-12:p;-15:f;-18:a;-21:z;-24:y';

//===================================================================
set vQVDPath=[lib://OLAP (fixmt_stefanovich)/];
//set vQVDPath=[lib://UT-PLAYH (fixmt_esipovich)/]
set vExcelPath=[lib://Excel (fixmt_stefanovich)/];
//===================================================================
let FullReload=0; //Полная или частичная перегрузка
//===================================================================
let DateStart = date(AddYears(MakeDate((2024),1,1),2000));
let DateFinish = date(AddYears(today(1)-1,2000));
let RollBackMonthCount = IF(FullReload=1,23,3);
//let RollBackMonthCount = IF(FullReload=1,35,IF(match(num(WeekDay(today(2))),5,6),35,3)); 
 
//===================================================================
LIB CONNECT TO 'UT-PLAYH (fixmt_stefanovich)'; //Продуктив
//LIB CONNECT TO 'UT-PLAYH (fixmt_esipovich)';
//===================================================================


// Exit script;


//$tab ДокументыСостав


/*
Документ.РеализацияТоваровУслуг.Товары (_Document299_VT5114)		
Документ.ОтчетОРозничныхПродажах.Товары (_Document270_VT3640)		
Документ.ВозвратТоваровОтПокупателя.Товары (_Document197_VT1211)    
*/

let DateInc = DateStart;
let DateLoadTo = DateFinish; 

do
	let DateFrom = DateInc; 
	let DateTo = MonthEnd(DateInc);
	let DateToSQL = date(MonthEnd(DateInc)+1);
	let FileSuffix = Text(date(AddYears(DateInc,-2000),'YYYY_MM'));
	let InRollBack  = (DateInc>=AddMonths(DateLoadTo, -RollBackMonthCount));


// if InRollBack or isnull(FileSize('$(vQVDPath)/_Document/_Document299_VT5114/_Document299_VT5114_$(FileSuffix).qvd')) then
	
// TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

// //Документ.РеализацияТоваровУслуг.Товары 
// _Document299_VT5114:
// load *;
// ;
// SQL SELECT 
// 	*
// FROM "UT-PLAYH".dbo."_Document299_VT5114"
// inner join
// "UT-PLAYH".dbo."_Document299"
// on 
// _Document299_VT5114._Document299_IDRRef=_Document299._IDRRef
// where Convert(date,_Date_Time,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,_Date_Time,104)< Convert(date,'$(DateToSQL)',104)
// and _Posted=01 and _Marked=00
// ;

// store _Document299_VT5114 into [$(vQVDPath)/_Document/_Document299_VT5114/_Document299_VT5114_$(FileSuffix).qvd](qvd);
// drop table _Document299_VT5114;

// ENDIF

// if InRollBack or isnull(FileSize('$(vQVDPath)/_Document/_Document270_VT3640/_Document270_VT3640_$(FileSuffix).qvd')) then
	
// TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

// //Документ.ОтчетОРозничныхПродажах.Товары 
// _Document270_VT3640:
// load *;
// ;
// SQL SELECT 
// 	*
// FROM "UT-PLAYH".dbo."_Document270_VT3640"
// inner join
// "UT-PLAYH".dbo."_Document270"
// on 
// _Document270_VT3640._Document270_IDRRef=_Document270._IDRRef
// where Convert(date,_Date_Time,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,_Date_Time,104)< Convert(date,'$(DateToSQL)',104)
// and _Posted=01 and _Marked=00
// ;

// store _Document270_VT3640 into [$(vQVDPath)/_Document/_Document270_VT3640/_Document270_VT3640_$(FileSuffix).qvd](qvd);
// drop table _Document270_VT3640;

// ENDIF

// if InRollBack or isnull(FileSize('$(vQVDPath)/_Document/_Document197_VT1211/_Document197_VT1211_$(FileSuffix).qvd')) then
	
// TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

// //Документ.ВозвратТоваровОтПокупателя.Товары 
// _Document197_VT1211:
// load *;
// ;
// SQL SELECT 
// 	*
// FROM "UT-PLAYH".dbo."_Document197_VT1211"
// inner join
// "UT-PLAYH".dbo."_Document197"
// on 
// _Document197_VT1211._Document197_IDRRef=_Document197._IDRRef
// where Convert(date,_Date_Time,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,_Date_Time,104)< Convert(date,'$(DateToSQL)',104)
// and _Posted=01 and _Marked=00
// ;

// store _Document197_VT1211 into [$(vQVDPath)/_Document/_Document197_VT1211/_Document197_VT1211_$(FileSuffix).qvd](qvd);
// drop table _Document197_VT1211;

// ENDIF

// if InRollBack or isnull(FileSize('$(vQVDPath)/_Document/_Document383_VT7745/_Document383_VT7745_$(FileSuffix).qvd')) then

// TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

// //Документ.nwpРекламнаяАкция.Товары 
// _Document383_VT7745:
// load *;
// ;
// SQL SELECT 
// 	*
// FROM "UT-PLAYH".dbo."_Document383_VT7745"
// inner join
// "UT-PLAYH".dbo."_Document383"
// on 
// _Document383_VT7745._Document383_IDRRef=_Document383._IDRRef
// where Convert(date,_Date_Time,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,_Date_Time,104)< Convert(date,'$(DateToSQL)',104)
// and _Posted=01 and _Marked=00
// ;

// store _Document383_VT7745 into [$(vQVDPath)/_Document/_Document383_VT7745/_Document383_VT7745_$(FileSuffix).qvd](qvd);
// drop table _Document383_VT7745;

// ENDIF


//Документ.ЗаказПокупателя.ТабличнаяЧасть.Товары для ЯндексДоставки
if InRollBack or isnull(FileSize('$(vQVDPath)/_Document/_Document221_VT1951/_Document221_VT1951_$(FileSuffix).qvd')) then

TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

_Document221_VT1951:
load *;
;
SQL SELECT 
	*
FROM "UT-PLAYH".dbo."_Document221_VT1951"
inner join
"UT-PLAYH".dbo."_Document221"
on 
_Document221_VT1951._Document221_IDRRef=_Document221._IDRRef
where Convert(date,_Date_Time,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,_Date_Time,104)< Convert(date,'$(DateToSQL)',104)
and _Posted=01 and _Marked=00
;

store _Document221_VT1951 into [$(vQVDPath)/_Document/_Document221_VT1951/_Document221_VT1951_$(FileSuffix).qvd](qvd);
drop table _Document221_VT1951;

ENDIF



///////////

let DateInc = timestamp(AddMonths(DateInc, 1));
LOOP while not InMonth(DateInc, DateLoadTo, 1);	


//$tab РегистрыНакоплений


let DateInc = DateStart;
let DateLoadTo = DateFinish; 

do
	let DateFrom = DateInc; 
	let DateTo = MonthEnd(DateInc);
	let DateToSQL = date(MonthEnd(DateInc)+1);
	let FileSuffix = Text(date(AddYears(DateInc,-2000),'YYYY_MM'));
	let InRollBack  = (DateInc>=AddMonths(DateLoadTo, -RollBackMonthCount));	

if InRollBack or isnull(FileSize('$(vQVDPath)/_AccumRg/_AccumRg11284/_AccumRg11284_$(FileSuffix).qvd')) then
	
TRACE 	$(DateFrom) -- 	$(DateTo)-- $(DateToSQL);	

//РегистрНакопления.ПродажиСебестоимость для ЯндексДоставки
_AccumRg11284:
load *;
;
SQL SELECT 
	Convert(date,_Period,104) as Дата,
    [_RecorderTRef] as "Тип документа",
    _RecorderRRef,
    _Fld11285RRef as КодНоменклатура,
    _Fld11287_RRRef as _Document221_IDRRef, //ЗаказПокупателя
    Sum(_Fld11292) as Количество,
    Sum(_Fld11293)/Sum(_Fld11292) as Стоимость
FROM "UT-PLAYH".dbo."_AccumRg11284"
where Convert(date,_Period,104)>= Convert(date,'$(DateFrom)',104) and Convert(date,_Period,104)< Convert(date,'$(DateToSQL)',104)
Group by Convert(date,_Period,104), _RecorderRRef, _Fld11285RRef, _Fld11287_RRRef, _RecorderTRef
;

store _AccumRg11284 into [$(vQVDPath)/_AccumRg/_AccumRg11284/_AccumRg11284_$(FileSuffix).qvd](qvd);
drop table _AccumRg11284;

ENDIF

let DateInc = timestamp(AddMonths(DateInc, 1));
LOOP while not InMonth(DateInc, DateLoadTo, 1); //exit script;


//$tab РегистрыCведений


// РегистрСведений.ВерсииОбъектов для для ЯндексДоставки или LoyaMobile с временем промежуточных Статусов
_InfoRg8826_Status:
LOAD *;
SQL 
SELECT [_Fld8827_RRRef] as _Document221_IDRRef,
	MIN(CASE WHEN [_Fld8832] = N'Ожидает подтверждения' THEN DATEADD(YEAR, -2000, [_Fld8831]) END) AS ДатаПоступления,
    MIN(CASE WHEN [_Fld8832] = N'Подтвержден' THEN DATEADD(YEAR, -2000, [_Fld8831]) END) AS ДатаПодтверждения,
    MIN(CASE WHEN [_Fld8832] = N'Собран' THEN DATEADD(YEAR, -2000, [_Fld8831]) END) AS ДатаСборки
from [UT-PLAYH].dbo.[_InfoRg8826] where [_Fld8827_RRRef] in 
	(SELECT [_IDRRef] FROM [UT-PLAYH].dbo.[_Document221]
	WHERE ([_Fld1918RRef] = 0xB9E400155DF9F40611EFB3A0A092FDE6 OR [_Fld1918RRef] = 0x977E3CECEF19CCC511F00EE440C8DF7B OR ([_Fld1918RRef] = 0xB9A000155D1D6B2011ECA3943DE225A7 AND [_Fld21654] = 1))
    and [_Posted] = 01 and [_Marked] = 00 
    and DATEADD(YEAR, -2000, Convert(date,[_Date_Time],23)) > '30-09-2025 23:59:59')
group by [_Fld8827_RRRef];
    				// B9E400155DF9F40611EFB3A0A092FDE6 Яндекс Деливери Бай ООО
																				// 977E3CECEF19CCC511F00EE440C8DF7B Loya mobile //B9A000155D1D6B2011ECA3943DE225A7 AND _Fld21654 = 1 Website
store _InfoRg8826_Status into [$(vQVDPath)/_InfoRg/_InfoRg8826_Status.qvd](qvd);
drop table _InfoRg8826_Status;

//exit script;

// РегистрСведений.ВерсииОбъектов для ЯндексДоставки или LoyaMobile статус "Аннулирован" или для LoyaMobile статус "Просрочен"
_InfoRg8826:
LOAD *;
SQL
Select t1._Document221_IDRRef, t1.Дата, t1.Автор, d.[_Fld1929RRef] as КодСтатусЗаказ 
from ( 
SELECT ir.[_Fld8827_RRRef] as _Document221_IDRRef, ir.[_Fld8830_RRRef] as Автор,  DATEADD(YEAR, -2000,Convert(date,ir.[_Fld8831],104)) as Дата, 
Row_Number() over (partition by ir.[_Fld8827_RRRef] order by ir.[_Fld8828] desc ) as NN
from [UT-PLAYH].dbo.[_InfoRg8826] ir 
where ir.[_Fld8827_RRRef] in (SELECT [_IDRRef] FROM [UT-PLAYH].dbo.[_Document221]
WHERE ([_Fld1929RRef] = 0xB3317DF3BA84E9E9455BB4C811186CD9 or [_Fld1929RRef] = 0x92DEF361C7C96BF543AA190705C0595D or [_Fld1929RRef] = 0xA8E66861BEFCE5BA48C9043F3813A1B8) 
		and [_Date_Time] >= '4024-11-07' and [_Posted] = 1 and [_Marked] = 0)
) as t1 
left join [UT-PLAYH].dbo.[_Document221] as d on t1._Document221_IDRRef = d.[_IDRRef]
where NN=1;

store _InfoRg8826 into [$(vQVDPath)/_InfoRg/_InfoRg8826.qvd](qvd);
drop table _InfoRg8826;

//exit script;




